// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Ch_11_Dal.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241205191640_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 84.400000000000006,
                            Title = "Deniz Feneri"
                        },
                        new
                        {
                            Id = 2,
                            Price = 159.0,
                            Title = "Sol Ayağım"
                        },
                        new
                        {
                            Id = 3,
                            Price = 190.0,
                            Title = "Simyacı"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
